### ISSUE TITLE
eth_call doesn't support integer for block number on reth client, only block hash 

### ISSUE THREAD

**Issue by AntonieDavid** [paradigmxyz/reth#10869]
### Describe the bug

While sending `eth_call` request to a reth node, this is the following output `{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"Invalid params","data":"invalid type: integer 20689053, expected Block identifier following EIP-1898 at line 2 column 12"}}`. The `eth_call` method parameters have different value types compared to geth client.

### Steps to reproduce

Reth request:
```
curl https://eth-mainnet.public.blastapi.io -H "Content-Type: application/json" -d '{
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [
    {
      "to": "0x5ba1e12693dc8f9c48aad8770482f4739beed696",
      "data": "0xbce38bd70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bb4aaaf8caa1a575b43e7673e5b155c1c5a8bc1300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000084dbdbb51b00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000"
    },
    20689053
  ],
  "id": 1
}'
```

Reth response:
`{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"Invalid params","data":"invalid type: integer 20689053, expected Block identifier following EIP-1898 at line 2 column 12"}}`

Geth request on quicknode:
```
curl https://red-omniscient-wind.quiknode.pro/c0a31e98a2b1488dd9fdfc3d3f9952597e90eb05 -H "Content-Type: application/json" -d '{
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [
    {
      "to": "0x5ba1e12693dc8f9c48aad8770482f4739beed696",
      "data": "0xbce38bd70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bb4aaaf8caa1a575b43e7673e5b155c1c5a8bc1300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000084dbdbb51b00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000"
    },
    20689053
  ],
  "id": 1
}'
```

Geth response:
`{"jsonrpc":"2.0","id":1,"result":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000"}`

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 1.0.4
Commit SHA: e24e4c773d7571a5a54dba7854643c02d0b0a841
Build Timestamp: 2024-08-07T10:40:25.003240211Z
Build Features: jemalloc
Build Profile: maxperf

### What database version are you on?

2024-09-12T17:10:00.114253Z  INFO Initialized tracing, debug log directory: /root/.cache/reth/logs/mainnet
Current database version: 2
Local database version: 2

### Which chain / network are you on?

ethereum mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by emhane** [comment]
this was fixed in https://github.com/paradigmxyz/reth/pull/7416, updating your node to latest release should fix it

**Comment by AntonieDavid** [comment]
@emhane I've manually tested this on a node with v1.0.6 and still experiencing the same issue
`curl localhost:8545 -H "Content-Type: application/json" -d '{
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [
    {
      "to": "0x5ba1e12693dc8f9c48aad8770482f4739beed696",
      "data": "0xbce38bd700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000
00000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000bb4aaaf8caa1a575b43e7673e5b155c1c5a8bc13000000000000000000000000000000000000000
00000000000000000000000400000000000000000000000000000000000000000000000000000000000000084dbdbb51b00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000
000000000000000000000000000000002000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000
0000000000000000000000000"
    },
    20689053
  ],
  "id": 1
}'


{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"Invalid params","data":"invalid type: integer `20689053`, expected Block identifier following EIP-1898 at line 2 column 12"}}


root@eth-archive-mainnet-1-euc1:~# reth --version
reth Version: 1.0.6
Commit SHA: c228fe15808c3acbf18dc3af1a03ef5cbdcda07a
Build Timestamp: 2024-09-05T08:19:49.445231351Z
Build Features: jemalloc
Build Profile: maxperf`

**Comment by emhane** [comment]
the block number should be in hexadecimal format @AntonieDavid

**Comment by AntonieDavid** [comment]
Got it, thanks for your support @emhane
